### ISSUE TITLE
Read-Only sessions (currently not possible)

### ISSUE THREAD

**Issue by diovudau** [jackaudio/new-session-manager#30]
Read-only sessions are useful: Templates to use with the _Dupliate_ command or a measure to prevent accidental changes including file access-timestamps (	`sudo chattr -R +i SESSION-DIRECTORY` ) 
They can also happen by real permission errors: Be it a network mount, files from another linux-user, FUSE mounts of an archived .tar session and more.

Currently nsmd will not load such sessions. The error message is a false-positive lockfile, because the lockfile function is testing with a write attempt. 

There are several solutions to this. Some of the following ideas I consider already good, some are here only for completeness-sake. It is assumed that a save-attempt to a read-only resource will not be a problem for any client.

- Remove lockfiles completely
- On session load only test if the lockfile exists, not if writing it would work.
- Test if write protected, if true do not test for lockfile (and possible further measures such as ignoring OSC-save messages)
- An explicit read-only nsmd mode. Either global as commandline option or available as OSC-switch between sessions.  This must delete all OSC save commands, but will still _not_ prevent clients saving on their own.  Meaning: this is NOT a solution of protecting your sessions against accidental saves.
- Explicitly forbid read-only scenarios through the API document. Advice workarounds like copying a session manually before starting NSM or fancy linux solutions like virtual filesystems that automagically forget any written changes and do not touch the original data.

My favourites are 
* removing lockfiles complety. At the moment they are broken ( https://github.com/linuxaudio/new-session-manager/issues/31 ) and not used.  I like it because it is a simple solution that offers the most flexibility for all kinds of future usecases. But it also burdens the user with preventing opening sessions twice with two different servers.
* Test for write-permissions, switch into a more forgiving internal mode. This is a more complex and therefore a source for new bugs but allows keeping lockfiles. If implemented 100% correctly this is what a user would expect.

**Comment by falkTX** [comment]
2nd option might be best, keeping the lockfile, but setting session as read-only if the lock file creation fails.

**Comment by diovudau** [comment]
Lockfiles are now repaired.  This removes the block to work on this feature.
Next phase is testing what happens under various circumstances of read-only sessions, such as file permissions or operating system security features. Reports are welcome.

**Comment by diovudau** [comment]
With commit 2ff0b51df2437af3bd8a2a830ceefa1c28938835  , together with the lock file fix, nsmd can now handle write protected session files. Detecting such a session file it will not send a save broadcast to clients.

This enables read-only sessions and template-sessions.
