### ISSUE TITLE
[Discussion] Remember client running status (running, stopped) in session save?

### ISSUE THREAD

**Issue by diovudau** [jackaudio/new-session-manager#33]
Consider this a discussion:

Several people asked for the option to save if a client was currently running or not. As a result when a session gets reloaded these programs should not start on their own.

This needs more investigation and actual user stories. 
Is this actually needed or are all people thinking of the same usecase? Will something go wrong? break compatibility? 

This feature is dependent on a decision how to handle saving additional data:  https://github.com/linuxaudio/new-session-manager/issues/32

**Comment by falkTX** [comment]
I think we need to solve the situation of jackpatch before we can tackle this. Otherwise we lose the connections, which is very frustrating.

I think it is best to try to keep everything in the same file, if we manage to make that work.
Only create new file if there is absolutely no other way.

**Comment by diovudau** [comment]
This will not get implemented. It is the kind of feature-creep we should avoid.
I don't think there is an actual usecase for this that cannot better be handled by internal muting, bypassing or disconnecting JACK ports.
