### ISSUE TITLE
new session manager on win/mac

### ISSUE THREAD

**Issue by Reaper10** [jackaudio/new-session-manager#49]
Will the new session manager be available for windows and or mac os?

**Comment by falkTX** [comment]
On windows, very unlikely, but might be doable for macOS.
The new-session-manager core team heavily disapproves and dislikes Apple's treat of users (and developers too), so our motivation to do anything macOS-related is pretty low. pull requests should be okay though.

**Comment by diovudau** [comment]
The technological problem of porting the session manager to another OS is also the lesser one. Without explicit client support over the OSC protocol NSM is pointless. The number of linux program that do is still small. How many of them exist in win/mac? 
How likely is it that native windows programs like Reaper (example inspired by OPs name) will support it? 
Actually... Reaper is pretty independent, that chance is above average for proprietary software. But let's say Cubase, Logic or even freeware like "VSTHost".

**Comment by diovudau** [comment]
If anyone wants to further discuss this, please re-open. But everyone that showed productive interest in the last 2 years NSM was not interested in this.
