### ISSUE TITLE
Legacy-GUI: Sessions label smears out upon rescaling

### ISSUE THREAD

**Issue by theGreatWhiteShark** [jackaudio/new-session-manager#57]
When shrinking the window of the legacy GUI to a size not sufficient for the "Sessions" label to be fully displayed and enlarging the window again afterwards the label gets smeared. (Observed in i3 4.17.1)

![smeared_session](https://user-images.githubusercontent.com/14164547/96242943-5e88aa00-0fa4-11eb-975e-14a0ef6e1931.png)

**Comment by diovudau** [comment]
Thanks for letting us know. This is a low priority bug that will most likely be fixed late, as a surprise or by avoiding the problem (harder resize constraints). Thank you for your patience :)

**Comment by theGreatWhiteShark** [comment]
This one seems to be a FLTK bug. At least I was not able to spot anything suspicious in the code or to fix issue by tweaking the it.

**Comment by diovudau** [comment]
I still have that as well.  We can simply let that slide for the moment, until somebody is really bored. Bug stays open of course.

**Comment by diovudau** [comment]
In the mean time the FLTK window got a minimum size, so that this issue will be circumvented.
