### ISSUE TITLE
server warning sessions folder

### ISSUE THREAD

**Issue by grammoboy2** [jackaudio/new-session-manager#84]
The server warns when a user uses a other sessions folder then it is recommended by the developer with a recent added patch apparently? What if the user sets NSM_DIR in it's environment? I saw Agordejo is quite obtrusively questioning the user every time to change it's folder (without a option to turn it off?). Imho that wouldn't be the right thing to do for the server. Setting a NSM_DIR in the environment, gives the user the freedom to choose the preferred location, which is a good thing I think. My two cents.

**Comment by diovudau** [comment]
It is the right thing to do and will stay that way.
"NSM_DIR" is not a supported environment variable.  

Just link your xdg dir to ~/NSM Sessions

**Comment by grammoboy2** [comment]
Could be an idea then. Default to whatever is the 'right thing'. But check if NSM_DIR is set first.
