### ISSUE TITLE
New extensions shouldn't use the /nsm prefix in the osc address

### ISSUE THREAD

**Issue by grammoboy2** [jackaudio/new-session-manager#97]
https://github.com/Houston4444/RaySession/issues/134
I saw that Raysession has added a extension and uses the /nsm prefix for it's address. I think that should be avoided. I would say, only use the prefix /nsm for the original non-session-manager api and use a other address for a new or custom extension. This way it's clear what the original core api is and then it's up to the manager GUI which extra extensions to adopt. In a ideal world, non-session-manager would still work after new developments (backward compatible*).

/raysession/client/...
/newsm/client/...

What RaySession is doing here needs extra caution, cause it add things to the 'nsm client api' (adds a :monitor: capability if I understand it correctly). At least it should be very clear imho that such thing is RaySession specific at the moment. Using /nsm as prefix violates that.

*That's why imho the change to end the session listing would be best reverted, cause it  breaks backward compatibility without a real need for it. "Done." vs " ". It's pure code aesthetics/ preference. 

FYI, reporting and closing.

**Comment by dvzrv** [comment]
> FYI, reporting and closing.

Can you please stop spamming this issue tracker? People are getting a lot of random mails because of this lately.
This is not your personal pet project issue tracker.

**Comment by grammoboy2** [comment]
These are not random issues and people are not getting random mails, but as you wish.
